install-gchart:
	echo "instals the gcarts in the rig t location"

poor-mans-web:
	echo "installs a very simple verion of a web server that runs the code. Please not that it may conflict with your current existing webserver and could destroy things, so only execute this if you just want to try this ourt ona vanilla ubuntu system that is not used for anything els. This is essentialy a way to test our software without you having to investigate time in how to integrate it into a proper web server. This is not a production web server."
